### ISSUE TITLE
[BUG] CodeGlancePro preventing debugging

### ISSUE THREAD

**Issue by Coolicky** [Nasller/CodeGlancePro#87] opened 2023-08-08 08:45 UTC
## 1. Which Glance version and IDEA version?
CodeGlancePro: 1.6.8
Rider: 2023.2 (232.8660.212)

## 2. Could you show Glance config picture and minimap picture?
![image](https://github.com/Nasller/CodeGlancePro/assets/45921848/91dd70fd-09c8-479b-bd06-f38117a6c0a5)
![image](https://github.com/Nasller/CodeGlancePro/assets/45921848/1c20bd1f-85bf-43bc-a2dd-1488cce1eb16)

## 3. What steps will reproduce the issue?
Updated CodeGlance to 1.6.8. Then tried debugging from Rider.
First i get a following popup
![image](https://github.com/Nasller/CodeGlancePro/assets/45921848/568e39be-4450-46cd-aad8-0eece1493b28)

Bug report stack.
`java.lang.IndexOutOfBoundsException: Wrong line: 0. Available lines count: 0
	at com.intellij.openapi.editor.ex.util.SegmentArray.getSegmentEnd(SegmentArray.java:192)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter$HighlighterIteratorImpl.getEnd(LexerEditorHighlighter.java:644)
	at com.nasller.codeglance.render.FastMainMinimap.refreshRenderData(FastMainMinimap.kt:237)
	at com.nasller.codeglance.render.FastMainMinimap.doInvalidateRange(FastMainMinimap.kt:472)
	at com.nasller.codeglance.render.FastMainMinimap.resetRenderData(FastMainMinimap.kt:300)
	at com.nasller.codeglance.render.FastMainMinimap.access$resetRenderData(FastMainMinimap.kt:44)
	at com.nasller.codeglance.render.FastMainMinimap$rebuildDataAndImage$1.invoke(FastMainMinimap.kt:89)
	at com.nasller.codeglance.render.FastMainMinimap$rebuildDataAndImage$1.invoke(FastMainMinimap.kt:89)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:74)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:193)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:789)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:759)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

Disabling CodeGlance fixes the issue.

**Comment by Nasller** [comment] 2023-08-08 08:57
Duplicate of #86

**Closed by Nasller** 2023-08-08 08:57 UTC
Labels: bug
