### ISSUE TITLE
Misaligned scrollbar rectangle that indicated code currently shown on screen

### ISSUE THREAD

**Issue by dydzio0614** [Nasller/CodeGlancePro#40] opened 2022-07-25 08:45 UTC
As in title. Included screenshots show examples of the issue. I am using macOS Monterey

Answers to standard questions:
1. Which Glance version and IDEA version? Jetbrains Rider 2022.1.2, glance version 1.4.5

2. Do you enabled reader mode option? No

3. Could you show Glance config picture and minimap picture?
![Config](https://user-images.githubusercontent.com/9436577/180734494-fcb9709c-4865-44ff-a792-36f62b8beea9.png)
![Misaligned error stripe](https://user-images.githubusercontent.com/9436577/180734777-89332a8c-a5d6-4a54-82e2-7c086562439e.png)
![Code covers most of screen and scrollbar selection does not](https://user-images.githubusercontent.com/9436577/180735065-321cbbec-50b5-4986-9fd5-7c82988ffee0.png)

4. What steps will reproduce the issue? It just happens and is easily visible on larger source files

**Comment by Nasller** [comment] 2022-07-25 08:48
Duplicate of #7

**Closed by Nasller** 2022-07-25 08:48 UTC
Labels: bug
