### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by danny-su** [Nasller/CodeGlancePro#59] opened 2022-12-07 10:19 UTC
IntelliJ 2022.3 

java.lang.IllegalStateException: typeParameters == null for SimpleFunctionDescriptorImpl mergeValues
	at org.jetbrains.kotlin.descriptors.impl.FunctionDescriptorImpl.getTypeParameters(FunctionDescriptorImpl.java:304)
	at org.jetbrains.kotlin.idea.util.FuzzyType.toOriginal(FuzzyTypeUtils.kt:76)
	at org.jetbrains.kotlin.idea.util.FuzzyType.<init>(FuzzyTypeUtils.kt:62)
	at org.jetbrains.kotlin.idea.util.FuzzyTypeUtils.toFuzzyType(FuzzyTypeUtils.kt:51)
	at org.jetbrains.kotlin.idea.util.FuzzyTypeUtils.fuzzyExtensionReceiverType(FuzzyTypeUtils.kt:18)
	at org.jetbrains.kotlin.idea.util.ExtensionUtils.substituteExtensionIfCallable(ExtensionsUtils.kt:32)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.processSuitableExtensions$lambda-14(KotlinIndicesHelper.kt:250)
	at org.jetbrains.kotlin.idea.stubindex.KotlinStringStubIndexExtension.processAllElements(KotlinStringStubIndexExtension.kt:43)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.processSuitableExtensions(KotlinIndicesHelper.kt:258)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getCallableTopLevelExtensions(KotlinIndicesHelper.kt:172)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getCallableTopLevelExtensions$default(KotlinIndicesHelper.kt:163)
	at org.jetbrains.kotlin.idea.core.KotlinIndicesHelper.getCallableTopLevelExtensions(KotlinIndicesHelper.kt:159)
	at org.jetbrains.kotlin.idea.quickfix.ImportForMismatchingArgumentsFix.fillCandidates(AbstractImportFix.kt:855)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.collectSuggestionsForName(AbstractImportFix.kt:275)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.collectSuggestionDescriptors(AbstractImportFix.kt:246)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase.computeSuggestions$kotlin_idea(AbstractImportFix.kt:105)
	at org.jetbrains.kotlin.idea.quickfix.ImportFixBase$Factory.createAction(AbstractImportFix.kt:338)
	at org.jetbrains.kotlin.idea.quickfix.KotlinSingleIntentionActionFactory.doCreateActions(KotlinSingleIntentionActionFactory.kt:12)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActions(KotlinIntentionActionsFactory.kt:42)
	at org.jetbrains.kotlin.idea.quickfix.KotlinIntentionActionsFactory.createActionsForAllProblems(KotlinIntentionActionsFactory.kt:24)
	at org.jetbrains.kotlin.idea.base.fe10.codeInsight.Fe10QuickFixProviderImpl.createQuickFixes(Fe10QuickFixProviderImpl.kt:40)
	at org.jetbrains.kotlin.idea.base.fe10.codeInsight.Fe10QuickFixProviderImpl.createQuickFixes(Fe10QuickFixProviderImpl.kt:83)
	at org.jetbrains.kotlin.idea.base.fe10.codeInsight.Fe10QuickFixProviderImpl.createQuickFixes(Fe10QuickFixProviderImpl.kt:63)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.createFixesMap(ElementAnnotator.kt:191)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.createFixesMap$default(ElementAnnotator.kt:183)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsSameFactoryQuickFixes(ElementAnnotator.kt:81)
	at org.jetbrains.kotlin.idea.highlighter.ElementAnnotator.registerDiagnosticsQuickFixes(ElementAnnotator.kt:74)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.annotateQuickFixes(AbstractKotlinHighlightVisitor.kt:197)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:142)
	at org.jetbrains.kotlin.idea.highlighter.AbstractKotlinHighlightVisitor.analyze(AbstractKotlinHighlightVisitor.kt:49)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.nasller.codeglance.visitor.MyRainbowVisitor.analyze(MyRainbowVisitor.kt:16)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:307)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:274)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:397)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:396)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:372)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:370)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Nasller** [comment] 2022-12-07 10:49
have you update new version?

**Comment by Nasller** [comment] 2022-12-07 11:12
Duplicate of #58

**Closed by Nasller** 2022-12-07 11:12 UTC
Labels: bug
