### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by transentia** [Nasller/CodeGlancePro#105] opened 2023-09-29 06:51 UTC
1. Which Glance version and IDEA version?

IntelliJ IDEA 2023.3 EAP (Ultimate Edition)
Build #IU-233.8264.8, built on September 28, 2023
Licensed to IntelliJ IDEA EAP user: Bob Brown
Expiration date: October 28, 2023
Runtime version: 17.0.8.1+7-b1063.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.nasller.CodeGlancePro (1.7.5)
  com.intellij.spring.webflow (233.8264.8)
  com.intellij.plugin.adernov.powershell (2.1.0)
Kotlin: 233-1.9.0-release-358-IJ8264.8

3. Could you show Glance config picture and minimap picture?
<img width="923" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/105110/a5cf6950-6bb0-45c3-a170-6c513bcd8502">

4. What steps will reproduce the issue?
Just open a window that CG will opeate with.

Get multiple exceptions, all:

```
	at com.nasller.codeglance.panel.GlancePanel.paintSomething(GlancePanel.kt:293)
	at com.nasller.codeglance.panel.GlancePanel.paintComponent(GlancePanel.kt:279)
```

<img width="1591" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/105110/1cfce941-adf8-4e0a-9fae-6beba4f9e8b8">

**Comment by transentia** [comment] 2023-09-29 06:54
Also get this when the code lens shows:

```
	at com.nasller.codeglance.panel.scroll.CustomEditorFragmentRenderer$EditorFragmentPreviewPanel.getPreferredSize(CustomEditorFragmentRenderer.kt:105)
	at com.nasller.codeglance.panel.scroll.CustomEditorFragmentRenderer$EditorFragmentPreviewPanel.paintComponent(CustomEditorFragmentRenderer.kt:111)

```

**Comment by Nasller** [comment] 2023-09-29 06:56
Duplicate of #102

**Comment by transentia** [comment] 2023-09-29 06:56
Interesting: code lens will only show if the area representing the window contents is NOT over it:

Shows, causes exception:
<img width="824" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/105110/b73d0467-371d-490c-a64f-137ec6fee20a">

Won't show:

<img width="157" alt="image" src="https://github.com/Nasller/CodeGlancePro/assets/105110/51777b1a-b238-4817-b4fa-a15230d87ac7">

**Closed by Nasller** 2023-09-29 06:56 UTC
Labels: bug

**Comment by Nasller** [comment] 2023-09-29 07:02
> Interesting: code lens will only show if the area representing the window contents is NOT over it:
> 
> Shows, causes exception: <img alt="image" width="824" src="https://user-images.githubusercontent.com/105110/271493964-b73d0467-371d-490c-a64f-137ec6fee20a.png">
> 
> Won't show:
> 
> <img alt="image" width="157" src="https://user-images.githubusercontent.com/105110/271494035-51777b1a-b238-4817-b4fa-a15230d87ac7.png">

This is a normal function, and I will fix this error when JetBrains fixes their code lens
